### PR TITLE
Ensure optional Phoenix is optional

### PR DESCRIPTION
**Pull request by aerosol**
Phoenix is optional, yet the library fails to build as a dependency of non-phoenix project due to reliance on `Mix.Phoenix` at compile time.

### CODE REVIEW

**Comment by mhanberg** [comment]
Thanks for the PR! I’ll take a look at this when I get home, but I’m pretty sure that its fine. 

Out of curiosity, are you using Temple for a non-Phoenix web app or something else?

**Comment by aerosol** [comment]
@mhanberg I was looking for some API to generate SVG markup with, no webserver whatsoever :)

**Comment by mhanberg** [comment]
Have you tested this locally with your project?

I am curious if something has to be done with the form.ex and link.ex files. It might not though since those define macros, and they won't be expanded unless you use the macros.

**Comment by aerosol** [comment]
```
(carb)  ~/dev/punkcard $ mix deps
* temple (git@github.com:aerosol/temple.git)
  locked at ff86b4b (branch: compile-with-optional-deps)
  the dependency is not available, run "mix deps.get"

(carb)  ~/dev/punkcard $ mix deps.get
* Getting temple (git@github.com:aerosol/temple.git)
remote: Enumerating objects: 742, done.
remote: Total 742 (delta 0), reused 0 (delta 0), pack-reused 742 
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  mime 1.3.1
  phoenix_html 2.13.3
  plug 1.8.3
  plug_crypto 1.0.0
* Getting phoenix_html (Hex package)
* Getting plug (Hex package)
* Getting mime (Hex package)
* Getting plug_crypto (Hex package)
(carb)  ~/dev/punkcard $ iex -S mix
Erlang/OTP 21 [erts-10.3.5.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

(...snip...)

iex(1)> use Temple
Temple
iex(2)> temple do
...(2)>   g foo: :bar do
...(2)>     text_ "hello"
...(2)>   end
...(2)> end
{:safe, "<g foo=\"bar\"><text>hello</text></g>"}
```

**Comment by aerosol** [comment]
@mhanberg `phoenix_html` is not optional, so it should be fine

**Comment by aerosol** [comment]
It's just the tasks that are missing:

```
(carb)  ~/dev/punkcard $ mix help | grep temple
mix temple.convert         # Converts HTML to Temple syntax
mix temple.update_mdn_docs # Update the MDN documentation
```

**Comment by aerosol** [comment]
I think the same should be done for `Floki` BTW. Even though the task is available it won't work unless I explicitly add `floki` to my deps

**Comment by mhanberg** [comment]
@aerosol Thanks for the contribution. I've released the fix under v0.4.3

**Pull request merged**
