### PR TITLE
Module based Component API

### PR DESCRIPTION
**Pull request by mhanberg**

### CODE REVIEW

**Comment by hfjallemark** [comment]
I actually liked the previous approach better, a bit too much boilerplate for my taste here (e.g. `defmodule` + `@behavior` + `@impl` + `render` + `quote`).

```elixir
div class: "flex #{@temple[:class]}", id: @id do
  @children
end
```

feels so much simpler and more like your regular templates (which leads to easier refactorings) than:

```elixir
defmodule MyAppWeb.Components.Flex do
   @behavior Temple.Component

   @impl Temple.Component
   def render do
     quote do
       div class: "flex #{@temple[:class]}", id: @id do
         @children
       end
     end
   end
 end
```

**Comment by mhanberg** [comment]
@hfjallemark I think this approach will make it simpler to expand the capabilities for passing arguments to a component and colocate helper functions.

I'm imagining an API where you could write something like this.

```elixir
defmodule MyAppWeb.Components.ProfileCard do
   use Temple.Component
   
   def yell_name(name), do: String.upcase(name)

   render(name, email, opts) do
     div do: ProfileCard.yell_name(@name)
     div do: @email
     
     section do
       @children
     end
   end
 end
```

**Comment by hfjallemark** [comment]
That looks a lot better actually! Is `render` a macro that hides some of the boilerplate?

Are the arguments different from the props? In your example you have `name` and `email` arguments and also `@name` and `@email` props.

**Comment by mhanberg** [comment]
render would remove some boiler plate, yeah. 

This is just an idea so far, I'll see what's possible when I start implementing it.

**Pull request merged**
