### PR TITLE
Add support for component parameters

### PR DESCRIPTION
**Pull request by zimt28**
Adds support for component params:

```elixir
defcomponent :heading, [title] do
  h1 title
  span "With " <> @props
end

temple do
  heading "Heading", props: "props"
end
```

I haven't done meta programming before, so there might be a better way to implement. Thanks for Temple!

### CODE REVIEW

**Comment by mhanberg** [comment]
Hi, thanks for the contribution! In the future, please open an issue for discussion before submitting a PR.

I am not sure that this adds much value to the API over passing in params, do you mind sharing your rationale for this type of API? I don't think Temple is in it's final form yet, so I am open to changes as long as they are well thought out and have merit.

My thoughts on the API as it is: If you are to define components that take normal-ish arguments, it would be better to define them like functions or macros.

```elixir
defcomponent heading(title) do # this looks more like a normal func/macro definition
  h1 title
  span "With " <> @props
end
```

While the params that they currently take are slightly "magic", I don't think it is as confusing as having some arguments magically defined while having others explicitly defined.

**Comment by zimt28** [comment]
Hi! You're right, `defcomponent heading(title) do` makes much more sense and looks much better as well. Unfortunately, I don't know how to implement it 😄 

The reason for params is that I don't think labelled props always make sense.

Let's imagine a `button` component:
```elixir
button title: "Title", link_to: some_path(@conn, :index), style: :primary)
```

I feel like `link_to` and `style` are options, while the `title` is the main param for the component.

Or maybe a `breadcrumbs` component:
```elixir
breadcrumbs do
  breadcrumb title: "Home"
  breadcrumb title: "Contacts"
end
```

There's no need for specifically adding the label `title` here, this would be much cleaner:
```elixir
breadcrumbs do
  breadcrumb "Home"
  breadcrumb "Contacts"
end
```

**Comment by zimt28** [comment]
Update: Was quite easy :)

**Comment by mhanberg** [comment]
I don't think I'm on board yet, but I really appreciate the effort you've put into this PR.

I'm going to give it a day or two sink in and I'll let you know if I still feel the same way.

**Comment by zimt28** [comment]
I agree that having both normal params and _magic_ props can be confusing. I've changed my application's code to use regular params in a lot of places now and I like it – it's just how I would write regular functions now. 

[`Temple.Html`](https://hexdocs.pm/temple/Temple.Html.html#content) and [`Temple.Form`](https://hexdocs.pm/temple/Temple.Form.html#content) both offer components with normal props, so it feels wrong not being able to write custom components like this as well.

I'm wondering how having both params and magic props can be made more obvious. Maybe good documentation is sufficient? This would still confuse people who just browse the code, but I couldn't figure out a better api yet.

**Comment by mhanberg** [comment]
After some thought, I am deciding to not move forward with this change.

I want to say I appreciate the contribution and please do not hesitate to bring more ideas to the table! They are always welcome.

**Comment by zimt28** [comment]
Fine with this, even though I still like it I didn't end up using it in as many places as I thought I'd do 😃

**Pull request closed without merging**
