### PR TITLE
Add @props access to components

### PR DESCRIPTION
**Pull request by zimt28**
Add feature #63.

### CODE REVIEW

**Comment by mhanberg** [comment]
Please add documentation for this enhancement

**Comment by zimt28** [comment]
Sure. Currently props are referred to as `assigns` in the docs. Should we use `@assigns` instead of `@props`?

**Comment by mhanberg** [comment]
Good catch. Let's go with assigns.

Can you you change the terminology used in the code in addition to the documentation?

**Comment by zimt28** [comment]
> Let's go with assigns.

I just checked again and in the Temple source `props` is being used everywhere, `assigns` is just being used in the documentation. I'd leave the code as `props` for now and document as `assigns` - this leads to inconsistency but at least "consistent inconsistency". This issue can then be resolved later, what do you think?

**Pull request merged**
